version: '3.7'

services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: roott
    ports:
      - "5432:5432"

  